// Workbook-only explanations derived from the supplied Vision Quest text,
// Lesson 3-1/3-2 Exercises and their answer/commentary sections (pp.16–20).
// The original question text and original answer/alternative strings stay untouched.
export const originalPoints: Record<number, string> = {
  2301: 'every Saturday は現在の習慣を表す。主語 My niece に合わせて comes とし、「我が家に」は to my house。',
  2302: 'be over は「終わった状態である」。今の状態を表す現在形 is を使う。原問題の空欄数と解答例の不整合には注記を付けている。',
  2303: '「所有している」という現在の状態は owns または has。日本語の「している」につられて進行形にしない。',
  2304: '今行っている動作を尋ねるので、現在進行形の疑問文 What are they doing ...? にする。',
  2305: '子どもの頃という過去の状態は was a child。その当時の習慣的な訪問は often visited。',
  2306: '「すでに使ってしまった」という現在に関わる完了を、have already spent で表す。spend の過去分詞は spent。',
  2307: 'なくしたのは過去なので lost。父が買ってくれたのはそれより前の出来事として had bought を使う。',
  2308: '帰宅した過去の時点に進行中だった動作は was talking。電話で話すのは talk on the phone。',
  2309: '「よく質問をしていました」という過去の習慣を asked で表す。ask 人 questions の語順。',
  2310: 'now の時点で進行中の動作を現在進行形で表す。主語は Tom and John の2人なので are playing。',
  2311: '今朝起きた過去の時点に雪が降っていたので、過去進行形 was snowing。',
  2312: 'every weekend が表す現在の習慣を現在形で表す。Haruka は三人称単数なので cooks。',
  2313: '体育館に着いた過去の時点より前に試合が終わっていた。had already finished で過去の基準時までの完了を表す。',
  2314: '駅まで急いだ過去の時点で、まだ到着していなかったことを had not arrived yet で表す。',
  2315: '気付いた時点より前の誤解を過去完了形 had misunderstood で表す。',
  2316: '「信じるようになってきた」は have come to believe。that 以下に信じる内容を続ける。',
  2317: '「その時が初めてだった」は It was the first time + 主語 + had + 過去分詞。',
  2318: '銀行に勤めているという現在の事柄を works で表す。work for a local bank の語順。',
  2319: 'after で出来事の順序が明らかなので、ここでは両方を過去形で表す。had a baby の had は have の過去形で、過去完了形ではない。',
  2320: '過去について was を使う。the first ... to visit ... は「訪問した最初の…」。資料の sitting U.S. president は「現職アメリカ大統領」。',
  2321: '週に2回の現在の習慣は takes。take piano lessons と twice a week を使う。',
  2322: '「最近、好きになってきた」は Recently, I have come to like ... で表す。',
  2323: '現在も進行している変化は is rising。資料は has been rising も別解として認めている。',
  2401: '前からの予定は is going to visit。資料では is planning to visit も別解として認められている。',
  2402: '準備や手配が進んでいる未来の予定を is leaving で表す。資料は will leave も認めている。',
  2403: '諦めないという意志は won\'t give up。until が導く時を表す副詞節では、未来のことでも comes と現在形を使う。',
  2404: '予定されている未来の出来事を will be discussing で表す。資料は plan to discuss も認めている。',
  2405: 'いつでも成り立つ事柄を現在形で表す。the earth は三人称単数なので goes または moves。',
  2406: '経過した年数は Ten years have passed since ...。since 以下には起点の過去の出来事を置く。',
  2407: 'おばが来た過去の時点まで読書を続けていたので、had been reading を使う。',
  2408: '彼が来た過去の時点までの待ち時間を述べる。資料では had not been waiting と had not waited の両方を認めている。',
  2409: '出会った時から今までの状態の継続は have loved。since we first met が継続の始まりを示す。',
  2410: '数日間降り続く雨を has been raining で表す。資料では has rained も別解として認めている。',
  2411: 'last year は過去の時点なので lived。ここでは過去の一定期間の生活を述べている。',
  2412: '今まで30分間待っているので have been waiting。資料は have waited も認めている。',
  2413: '会社に一度行った経験は has been to ... once。主語 My sister に合わせて has。',
  2414: '10年来の知り合いという、現在までの状態の継続を have known で表す。',
  2415: '来年の発売を表す未来表現。資料は will release のほか、is going to release、is releasing、plans to release も認めている。',
  2416: '「ちょうど出かけようとしていた」は was about to leave。when 以下にその時起きた出来事を続ける。',
  2417: 'be expected to + 原形を使う。「提出する」は hand in。主語 We なので are expected。',
  2418: '「起業しようと思っている」は is thinking of starting a business。of の後ろは動名詞 starting。',
  2419: '「会うのは久しぶり」は It\'s been a long time since ...。「最後に会った時」は since I last saw ...。',
  2420: '最近、便りを受け取っていないことを haven\'t heard from ... で表す。資料では recently / lately の両方を認めている。',
  2421: '過去のその時までの経験の否定は hadn\'t been to ... until then。',
  2422: '未来のある時点までの経験を will have been to で表す。条件を表す if 節では、未来のことでも go と現在形にする。',
  2423: '最後に楽しく過ごしてから長い時間がたった、と考えて It\'s been a long time since ... を使う。資料には現在完了形の否定を使う別解もある。',
};
